apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nodejs-pipeline-
spec:
  params:
    - name: repositoryUrl
      value: https://github.com/misanche/pipelines-nodejs
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
  